# Generated by Django 4.2.17 on 2025-02-05 06:59

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('url', models.FileField(upload_to=storage.models.user_directory_path)),
                ('file_size', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
